force-app/main/default/objects/ATM_Fee_in_other_currencies__mdt/ATM_Fee_in_other_currencies__mdt.object-meta.xml
<CustomObject>
    <label>ATM Fee in other currencies</label>
    <pluralLabel>ATM Fee in other currencies</pluralLabel>
</CustomObject>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <description>Used to store countries name</description>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Used to Store type of Product</description>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Cost_per_Calendar_Month__mdt/Cost_per_Calendar_Month__mdt.object-meta.xml
<CustomObject>
    <label>Cost per Calendar Month</label>
    <pluralLabel>Cost per Calendar Months</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cost_per_Calendar_Month__mdt/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Product_Info_Controller.cls
/*
Author: Nishant Mohan Wavhal
Created Date: 7/11/2022
Apex Class to give Product Info to LWC
*/
public with sharing class Product_Info_Controller {

    /* Method: cost_per_Calendar_Month 
    method returns specidic mdt specific to cost_per_Calendar_Month
    */
    @AuraEnabled(cacheable=true)
    public static MDT_ObjectWrapper cost_per_Services(Id caseId){
       MDT_ObjectWrapper mdtwrapper;
       Cost_per_Calendar_Month__mdt cp= new Cost_per_Calendar_Month__mdt();
       Card_Replacement_Cost__mdt cr = new Card_Replacement_Cost__mdt();
       ATM_Fee_in_other_currencies__mdt a = new ATM_Fee_in_other_currencies__mdt();
        
        String homecountry;
        String product;
        
        if(caseId !=null)
        {
            try{
            Case c=[select id ,ContactId,contact.home_Country__c,contact.Product__c from Case where id =:caseId limit 1];
           if(c!=null)
            { 
            if(c.ContactId!=null)
           {
            if(c.contact.home_Country__c!=null && c.contact.product__c!=null && c.contact.home_Country__c!='' && c.contact.product__c!='')
            {
             cp=Product_Info_Service.costpermonthservice(c.contact.home_Country__c,c.contact.product__c);
                        
             cr= Product_Info_Service.cardreplacementservice(c.contact.home_Country__c,c.contact.product__c);
                
             a=Product_Info_Service.atmfeeservice(c.contact.home_Country__c,c.contact.product__c);           
                
              homeCountry=c.contact.home_Country__c;
              product=c.contact.product__c;
            }
              else
              throw new CustomErrorException('500','Contact Value has an Error'); 
           }
            else
                throw new CustomErrorException('500','Contact Value is Null'); 
        }
            
        }
          
         Catch(Exception e)
         {
             System.debug(e.getmessage());
         }
        }
        if(cp!=null && cr!=null && a!=null)
        {
            
        mdtwrapper= new MDT_ObjectWrapper(homecountry,product,cp,cr,a);
        }
        else
           throw new CustomErrorException('500','Something went wrong'); 
        return mdtwrapper;
    }
  

}